@echo off
echo Backing up PROD to DMS_BACKUP...
if not exist DMS_BACKUP mkdir DMS_BACKUP
xcopy DMS DMS_BACKUP /E /I /Q /Y /EXCLUDE:exclude.txt

echo Updating PROD from PRE_AMMED...
echo Copying DMS...
xcopy PRE_AMMED\DMS DMS /E /I /Q /Y /EXCLUDE:exclude.txt
echo Copying home...
xcopy PRE_AMMED\home home /E /I /Q /Y /EXCLUDE:exclude.txt
echo Done. Please restart PROD containers if needed.
